### ISSUE TITLE
How to generate light transport map in training phase 1?

### ISSUE THREAD

**Issue by Jarvisss** [majita06/Relighting_in_the_Wild#1]
As far as I know, the transport map computed by PRT stores the SH coefficients at each vertex of the mesh, but not at each pixel, how do you obtain the transport vector at each pixel?

**Comment by yshhrknmr** [comment]
Thank you very much for your interest in our work. SH coefficients in light transport maps are calculated for each pixel, as done in our previous work:
http://kanamori.cs.tsukuba.ac.jp/projects/relighting_human/ 

For this computation, I developed a GPU-based renderer, but currently I haven't released the code yet.

Theoretically, my code emits rays at each pixel to evaluate the visibility function. However, this ray emission is computationally quite expensive, so I accelerate it by emitting rays in parallel.

**Comment by Jarvisss** [comment]
Hi, @yshhrknmr, thank you for your quick reply! 
I've read your previous work on siggraph asia 2018 [1].
In [1], Equation 7 illustrates that the irradiance E can be the dot product of transport vector T and the light vector L. 
![image](https://user-images.githubusercontent.com/16323003/138232415-13e6051d-9773-46c2-889f-ae783c791b11.png)

This is where I'm confused, E is defined on the surface of the mesh, I mean, isn't it? 

Best,
Jarvis

**Comment by yshhrknmr** [comment]
> This is where I'm confused, E is defined on the surface of the mesh, I mean, isn't it?

I'm not sure whether I understand your comment correctly, but in our case, the surface is rasterized into pixels, and E is calculated at each pixel.

**Comment by Jarvisss** [comment]
@yshhrknmr 
I read code of prt in the PiFu repo, are yours similar to theirs?
https://github.com/shunsukesaito/PIFu/blob/02a6d8643d3267d06cb4a510b30a59e7e07255de/apps/prt_util.py#L87-L123

**Comment by yshhrknmr** [comment]
Thanks for pointing out PIFu's code. Whereas they calculate SH coefficients per vertex, we calculate per pixel after rasterizing the surface into pixels.

**Comment by Jarvisss** [comment]
Thanks for your reply! I'll try to implement your transport map for my project, but if it is convenient if you could provide this part of the code, many thanks!

**Comment by yshhrknmr** [comment]
Indeed I received some requests to publish the code for calculating the light transport maps. At first, I planned to publish a (short) paper for it because it is pretty fast, but I couldn't manage my time so far. I haven't decided what to do yet.

**Comment by Jarvisss** [comment]
So if speed is not a problem, or not a care in my project, can I calculate per vertex SH coefficients and then rasterize them to get per pixel SH coefficients?

**Comment by yshhrknmr** [comment]
Yes, that's one option. You can linearly interpolate per-vertex SH coefficients to obtain per-pixel SH coefficients.

**Comment by Jarvisss** [comment]
Thanks a lot!
